# JSON logs Logstash
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/*.ndjson
  json.keys_under_root: true
  json.add_error_key: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: '${ES_USERNAME:elastic}'
  password: '${ES_PASSWORD:changeme}'

setup.ilm.enabled: auto
setup.ilm.rollover_alias: "bibliotecas-valencia"
setup.ilm.pattern: "{now/d}-000001"

xpack.monitoring.enabled: true
logging.to_files: false

setup:
  dashboards.enabled: false
  template.overwrite: false
  template.settings.index.number_of_shards: 1
  template.settings.index.number_of_replicas: 0